server {
    listen 80;

    # backend
    location /api/ {
        proxy_pass http://backend:8080;
    }

    # frontend
    location / {
        proxy_pass http://frontend:3000;
        # ホットリロードのためにWebSocketを通過していい設定を追加
        # nginxは安全のためにHTTP1.0を使っている。そのため、HTTP1.1にしてWebSocket対応バージョンにする。
        proxy_http_version 1.1;
        # nginxはデフォルトでプロキシ先にWebSocketに必要な2つのヘッダーを渡してくれないため設定
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
