server {
    listen 80;

    # backend
    location /api/ {
        # 末尾の「/」が重要
        proxy_pass http://backend:8080/;
    }

    # frontend
    location / {
        proxy_pass http://frontend:3000;
        # ホットリロードのためにWebSocketを通過していい設定を追加
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}